version: "3"
services:
  nginx:
    build: ./web/nginx
    ports:
      - "80:80"
    depends_on:
      - keystone
  keystone:
    build: ./web/keystone
    # ports:
    #   - "3000:3000"
    #   - "4000:4000"
    # volumes:
    #   - "./web/keystone:/usr/src/app"
    # command: npm run dev
    depends_on:
      - mongodb
      - redis
  mongodb:
    env_file: ./web/mongo/.env
    image: mongo:latest
    volumes:
      - "./web/mongo/data/db:/data/db/"
  redis:
    image: "redis:alpine"
    volumes:
      - "./web/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf

  # command: bash -c "npm update && npm install"
    

  # to start: docker-compose up

  # Docker Commands:
    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    # docker rmi $(docker images -a -q)

# Example of working host code
# sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /Users/james.miller/docker/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://10.9.126.211:8080/v1/scripts/E018295D1CF4082B7B23:1483142400000:53rurIg4AdrJNHK0MQF1SFILGE

