apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
      restartPolicy: Always
      nodeSelector:
        type: database
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    run: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    name: http
  selector:
    app: redis