# REDO EACH OF THE DATA FIELDS AS ENCRYPTED SECRETS
apiVersion: v1
kind: Secret
metadata:
  name: sketchfab-cms-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: J2tleXN0b25lJw==
  MONGO_INITDB_ROOT_USERNAME: J2FkbWluJw==
  COOKIE_SECRET: J2M5MTkxZTUxNDg4MzI2NDBlMmE5NDJlODE4YmQyNDRkZGYwNmFkZmZjYzQ3MjdmODkwYWM5Y2VkYTc2MGQzNzkzMGIzYzU1NzA1ZjRkN2FhNDQyMWNlNjVjOWJjMjUwZDUzNzc2ZWQwMDE0MTAxMmM4OGY4MWE4NmU5OGNmNzhkJw==
  CLOUDINARY_URL: J2Nsb3VkaW5hcnk6Ly8zMzM3NzkxNjcyNzY2NjI6XzhqYlNpOUZCM3NXWXJmaW1jbDhWS2gzNHJJQGtleXN0b25lLWRlbW8n
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmtleXN0b25lQG1vbmdvZGI=
  EMAIL_USERNAME: J21vbW9tb2RlbHM5OUBnbWFpbC5jb20n
  EMAIL_PASSWORD: J01vbWVudHVtOTkn
  REDIS_PORT: JzYzNzkn
  REDIS_HOST: J3JlZGlzJw==
  REDIS_PASSWORD: J2tleXN0b25lJw==
  REDIS_TTL: JzEyMDk2MDAn