module.exports = {
	COOKIE_SECRET: process.env.COOKIE_SECRET,
	CLOUDINARY_URL: process.env.CLOUDINARY_URL,
	MONGO_URI: process.env.MONGO_URI,
	EMAIL_USERNAME: process.env.EMAIL_USERNAME,
	EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
	REDIS_PORT: process.env.REDIS_PORT,
	REDIS_HOST: process.env.REDIS_HOST,
	REDIS_TTL: process.env.REDIS_TTL,
	REDIS_PASSWORD: process.env.REDIS_PASSWORD
}